# Generated by Django 5.0.1 on 2024-01-08 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='media/thumbnails'),
        ),
    ]
